### ISSUE TITLE
Configuration 

### ISSUE THREAD

**Issue by itbsStefan** [mvbasov/OMN#2]
Is it possible to setup an other datadir then storage/emulated/0/Android/data/net.basov.omn.b/files
Maybe like /storage/emulated/0/Documents/omnfiles
Or may any further plans to change things?

**Comment by mvbasov** [comment]
No. 
The OMN use as minimal as possible permissions.
The path storage/emulated/0/Android/data/net.basov.omn.b/files is package dedicated area which can be used without additional permission request.
To use /storage/emulated/0/Documents/omnfiles additional storage permission required.

**Comment by mvbasov** [comment]
For Android >13  storage/emulated/0/Android/media/net.basov.omn.b/ used for easy access to notes for another applications (like file managers)
